### ISSUE TITLE
Widget UI needs fixing

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/Rabbi_Ovadiah_Yosef_Calendar_App#7]
Currently the widget is just 6 textviews that update at either 30 minute intervals or when the next upcoming zman is. Whichever is first updates the textviews.

I tried making the textviews look nicer by adding padding and using LinearLayouts, however, the widget still has many issues in multiple formats. 

Text getting cut off is the biggest issue. That needs to be avoided at all costs.

**Comment by Elyahu41** [comment]
Here are some screenshots of common issues:

![Untitled](https://github.com/Elyahu41/RabbiOvadiahYosefCalendarApp/assets/47622014/a2caf879-bc53-44b6-ad57-2fddab4cadd6)

This picture shows how the bottom 3 textviews get cut off, I would Ideally like to have the hebrew date be shown instead:
![Untitled](https://github.com/Elyahu41/RabbiOvadiahYosefCalendarApp/assets/47622014/b19c4ca3-440f-4418-9cf4-08a8e857bc3a)

Something like this would look better if there is less space:
![Untitled](https://github.com/Elyahu41/RabbiOvadiahYosefCalendarApp/assets/47622014/b30db938-9c49-49d4-b1a1-bd399a57ecc2)

Also when the widget is expanded it does not take advantage of the extra space:
![Untitled](https://github.com/Elyahu41/RabbiOvadiahYosefCalendarApp/assets/47622014/c9e0d8be-21ac-45a1-896f-f70e9444476d)

**Comment by NightScript370** [comment]
Perhaps in the extra space we could add an analogue countdown to the next zman

**Comment by Elyahu41** [comment]
To help anyone who wants to help get started on this issue, look at the following files:

in activities:
ZmanimAppWidget.java

in res/layout:
zmanim_app_widget_preview.xml
zmanim_app_widget_horizontal.xml
zmanim_app_widget.xml

**Comment by NightScript370** [comment]
Shouldn't this be closed with the most recent updates?

**Comment by Elyahu41** [comment]
Was about to do it, I was just waiting to see if users had issues with the new update.

**Comment by Elyahu41** [comment]
This has been resolved as of commit bad2bee
